### ISSUE TITLE
Proto file missing

### ISSUE THREAD

**Issue by dark0n7** [HurroWorld/text-to-audio2face#1]
Hello!

I tried to test the repository, but ran into the problem of missing protocol file audio2face.proto

**Comment by HurroWorld** [comment]
You need to update the path in grpcClient.js with the path to the .proto file from your audio2face installation.

Eg:

```
const PROTO_PATH = "C:/Users/houar/AppData/Local/ov/pkg/audio2face-2023.2.0/exts/omni.audio2face.player/omni/audio2face/player/scripts/streaming_server/proto/audio2face.proto";
```
